# Very Good Analysis
include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    no_default_cases: false
    omit_local_variable_types: false
    avoid_types_on_closure_parameters: true
    prefer_relative_imports: true
    always_use_package_imports: false
    directives_ordering: true
    sort_pub_dependencies: false
